In [50]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import parselmouth
from parselmouth.praat import call
import glob

In [2]:
df = pd.read_csv('dataset11.csv')

In [3]:
df.head()

meanF0Hz  stdevF0Hz        HNR  localJitter  localabsoluteJitter  \
0  125.962625  22.497441  13.938221     0.019033             0.000151   
1  125.962625  22.497441  13.938221     0.019033             0.000151   
2  111.114278  21.143679  12.296702     0.031814             0.000288   
3  111.114278  21.143679  12.296702     0.031814             0.000288   
4  124.770779  29.371232  13.736238     0.025720             0.000207   

   rapJitter  ppq5Jitter  ddpJitter  localShimmer  localdbShimmer  \
0   0.007857    0.008625   0.023571      0.091795        0.848507   
1   0.007857    0.008625   0.023571      0.091795        0.848507   
2   0.013555    0.013621   0.040666      0.112481        1.041977   
3   0.013555    0.013621   0.040666      0.112481        1.041977   
4   0.011745    0.012533   0.035236      0.096023        0.951581   

   apq3Shimmer  apq5Shimmer  apq11Shimmer  ddaShimmer  status  
0     0.034620     0.048287      0.084348    0.103860     1.0  
1     0.034620     0.048287      0.084348    0.103860     1.0  
2     0.041326     0.059044      0.106803    0.123979     1.0  
3     0.041326     0.059044      0.106803    0.123979     1.0  
4     0.036093     0.050104      0.094874    0.108279     1.0

In [4]:
df.tail()

meanF0Hz  stdevF0Hz        HNR  localJitter  localabsoluteJitter  \
141  214.216909  38.864715  15.373564     0.016988             0.000079   
142  182.554190  44.447825  15.092618     0.019678             0.000108   
143  182.554190  44.447825  15.092618     0.019678             0.000108   
144  137.759284  24.790170  11.083001     0.028160             0.000205   
145  137.759284  24.790170  11.083001     0.028160             0.000205   

     rapJitter  ppq5Jitter  ddpJitter  localShimmer  localdbShimmer  \
141   0.008453    0.008099   0.025359      0.060868        0.629243   
142   0.009226    0.009401   0.027677      0.092794        0.876801   
143   0.009226    0.009401   0.027677      0.092794        0.876801   
144   0.011123    0.013622   0.033368      0.120958        1.129300   
145   0.011123    0.013622   0.033368      0.120958        1.129300   

     apq3Shimmer  apq5Shimmer  apq11Shimmer  ddaShimmer  status  
141     0.023691     0.028934      0.047617    0.071073     0.0  
142     0.040549     0.051243      0.080070    0.121647     0.0  
143     0.040549     0.051243      0.080070    0.121647     0.0  
144     0.046355     0.066205      0.116045    0.139065     0.0  
145     0.046355     0.066205      0.116045    0.139065     0.0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 146 entries, 0 to 145
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   meanF0Hz             146 non-null    float64
 1   stdevF0Hz            146 non-null    float64
 2   HNR                  146 non-null    float64
 3   localJitter          146 non-null    float64
 4   localabsoluteJitter  146 non-null    float64
 5   rapJitter            146 non-null    float64
 6   ppq5Jitter           146 non-null    float64
 7   ddpJitter            146 non-null    float64
 8   localShimmer         146 non-null    float64
 9   localdbShimmer       146 non-null    float64
 10  apq3Shimmer          146 non-null    float64
 11  apq5Shimmer          146 non-null    float64
 12  apq11Shimmer         146 non-null    float64
 13  ddaShimmer           146 non-null    float64
 14  status               146 non-null    float64
dtypes: float64(15)
memory usage: 17.2 KB


In [7]:
df.describe()

meanF0Hz   stdevF0Hz         HNR  localJitter  localabsoluteJitter  \
count  146.000000  146.000000  146.000000   146.000000           146.000000   
mean   168.792582   40.826633   13.761463     0.022456             0.000144   
std     31.205092   11.692267    1.988059     0.005942             0.000064   
min     99.176942   15.856715    7.896080     0.011022             0.000051   
25%    139.689970   34.365179   12.358663     0.018613             0.000094   
50%    178.219741   39.933612   13.757537     0.021499             0.000127   
75%    190.751972   48.146242   15.092618     0.026740             0.000180   
max    218.327218   81.862069   18.499974     0.038871             0.000348   

        rapJitter  ppq5Jitter   ddpJitter  localShimmer  localdbShimmer  \
count  146.000000  146.000000  146.000000    146.000000      146.000000   
mean     0.009721    0.010426    0.029164      0.091825        0.892749   
std      0.003042    0.003010    0.009127      0.020566        0.173982   
min      0.004204    0.004236    0.012612      0.054901        0.534262   
25%      0.007586    0.008099    0.022758      0.078274        0.774723   
50%      0.009791    0.010128    0.029373      0.089151        0.876801   
75%      0.011396    0.012758    0.034189      0.102565        0.996542   
max      0.017499    0.017930    0.052497      0.179428        1.531849   

       apq3Shimmer  apq5Shimmer  apq11Shimmer  ddaShimmer      status  
count   146.000000   146.000000    146.000000  146.000000  146.000000  
mean      0.034981     0.048540      0.084540    0.104943    0.424658  
std       0.009679     0.013158      0.021661    0.029036    0.495992  
min       0.019742     0.027809      0.043856    0.059226    0.000000  
25%       0.028235     0.039414      0.069240    0.084704    0.000000  
50%       0.033771     0.046513      0.081971    0.101313    0.000000  
75%       0.039932     0.055332      0.096072    0.119795    1.000000  
max       0.070886     0.103642      0.148077    0.212658    1.000000

In [32]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics

In [9]:
X = df.drop('status',axis=1)
y = df['status']

In [10]:
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size = 0.1, random_state = 0)

In [12]:
X_train.shape,y_train.shape

((131, 14), (131,))

In [41]:
model1 = LogisticRegression()
model2 = DecisionTreeClassifier()
model3 = SVC()
model4 = KNeighborsClassifier()
model5 = GaussianNB()

In [42]:
model1.fit(X_train, y_train)
model2.fit(X_train, y_train)
model3.fit(X_train, y_train)
model4.fit(X_train, y_train)
model5.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [43]:
from sklearn.ensemble import VotingClassifier

model = VotingClassifier(estimators=[('Log_R',model1),('DT',model2),('SVM', model3),
                                     ('KNN',model4),('GNB',model5)],voting = 'hard')

In [44]:
model.fit(X_train,y_train)

VotingClassifier(estimators=[('Log_R',
                              LogisticRegression(C=1.0, class_weight=None,
                                                 dual=False, fit_intercept=True,
                                                 intercept_scaling=1,
                                                 l1_ratio=None, max_iter=100,
                                                 multi_class='auto',
                                                 n_jobs=None, penalty='l2',
                                                 random_state=None,
                                                 solver='lbfgs', tol=0.0001,
                                                 verbose=0, warm_start=False)),
                             ('DT',
                              DecisionTreeClassifier(ccp_alpha=0.0,
                                                     class_weight=None,
                                                     criterion='gin...
                                  gamma=

In [45]:
train_score = model.score(X_train, y_train)
test_score = model.score(X_test, y_test)
print ('train accuracy =', train_score)
print ('test accuracy =', test_score)

train accuracy = 0.816793893129771
test accuracy = 0.7333333333333333


In [46]:
y_pred = model.predict(X_test)
y_pred

array([1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1.])

In [47]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
cm

array([[8, 1],
       [3, 3]], dtype=int64)

In [48]:
def measurePitch(voiceID, f0min, f0max, unit):
    sound = parselmouth.Sound(voiceID) # read the sound
    pitch = call(sound, "To Pitch", 0.0, f0min, f0max) #create a praat pitch object
    meanF0 = call(pitch, "Get mean", 0, 0, unit) # get mean pitch
    stdevF0 = call(pitch, "Get standard deviation", 0 ,0, unit) # get standard deviation
    harmonicity = call(sound, "To Harmonicity (cc)", 0.01, 75, 0.1, 1.0)
    hnr = call(harmonicity, "Get mean", 0, 0)
    pointProcess = call(sound, "To PointProcess (periodic, cc)", f0min, f0max)
    localJitter = call(pointProcess, "Get jitter (local)", 0, 0, 0.0001, 0.02, 1.3)
    localabsoluteJitter = call(pointProcess, "Get jitter (local, absolute)", 0, 0, 0.0001, 0.02, 1.3)
    rapJitter = call(pointProcess, "Get jitter (rap)", 0, 0, 0.0001, 0.02, 1.3)
    ppq5Jitter = call(pointProcess, "Get jitter (ppq5)", 0, 0, 0.0001, 0.02, 1.3)
    ddpJitter = call(pointProcess, "Get jitter (ddp)", 0, 0, 0.0001, 0.02, 1.3)
    localShimmer =  call([sound, pointProcess], "Get shimmer (local)", 0, 0, 0.0001, 0.02, 1.3, 1.6)
    localdbShimmer = call([sound, pointProcess], "Get shimmer (local_dB)", 0, 0, 0.0001, 0.02, 1.3, 1.6)
    apq3Shimmer = call([sound, pointProcess], "Get shimmer (apq3)", 0, 0, 0.0001, 0.02, 1.3, 1.6)
    aqpq5Shimmer = call([sound, pointProcess], "Get shimmer (apq5)", 0, 0, 0.0001, 0.02, 1.3, 1.6)
    apq11Shimmer =  call([sound, pointProcess], "Get shimmer (apq11)", 0, 0, 0.0001, 0.02, 1.3, 1.6)
    ddaShimmer = call([sound, pointProcess], "Get shimmer (dda)", 0, 0, 0.0001, 0.02, 1.3, 1.6)
    

    return meanF0, stdevF0, hnr, localJitter, localabsoluteJitter, rapJitter, ppq5Jitter, ddpJitter, localShimmer, localdbShimmer, apq3Shimmer, aqpq5Shimmer, apq11Shimmer, ddaShimmer

In [55]:
# create lists to put the results
file_list = []
mean_F0_list = []
sd_F0_list = []
hnr_list = []
localJitter_list = []
localabsoluteJitter_list = []
rapJitter_list = []
ppq5Jitter_list = []
ddpJitter_list = []
localShimmer_list = []
localdbShimmer_list = []
apq3Shimmer_list = []
aqpq5Shimmer_list = []
apq11Shimmer_list = []
ddaShimmer_list = []
parkinson_list = []



# Go through all the wave files in the folder and measure pitch
for wave_file in glob.glob("C:/Users/srees/OneDrive/Desktop/major_proj/ParkinsonIA-master/audio/SpontaneousDialogue/PD/ID13_pd_3_2_2.wav"):
    sound = parselmouth.Sound(wave_file)
    (meanF0, stdevF0, hnr, localJitter, localabsoluteJitter, rapJitter, ppq5Jitter, ddpJitter, localShimmer, localdbShimmer, apq3Shimmer, aqpq5Shimmer, apq11Shimmer, ddaShimmer) = measurePitch(sound, 75, 1000, "Hertz")
    file_list.append(wave_file) # make an ID list
    mean_F0_list.append(meanF0) # make a mean F0 list
    sd_F0_list.append(stdevF0) # make a sd F0 list
    hnr_list.append(hnr)
    localJitter_list.append(localJitter)
    localabsoluteJitter_list.append(localabsoluteJitter)
    rapJitter_list.append(rapJitter)
    ppq5Jitter_list.append(ppq5Jitter)
    ddpJitter_list.append(ddpJitter)
    localShimmer_list.append(localShimmer)
    localdbShimmer_list.append(localdbShimmer)
    apq3Shimmer_list.append(apq3Shimmer)
    aqpq5Shimmer_list.append(aqpq5Shimmer)
    apq11Shimmer_list.append(apq11Shimmer)
    ddaShimmer_list.append(ddaShimmer)


pred = pd.DataFrame(np.column_stack([mean_F0_list, sd_F0_list, hnr_list, localJitter_list, localabsoluteJitter_list, rapJitter_list, ppq5Jitter_list, ddpJitter_list, localShimmer_list, localdbShimmer_list, apq3Shimmer_list, aqpq5Shimmer_list, apq11Shimmer_list, ddaShimmer_list]),
                               columns=['meanF0Hz', 'stdevF0Hz', 'HNR', 'localJitter', 'localabsoluteJitter', 'rapJitter', 
                                        'ppq5Jitter', 'ddpJitter', 'localShimmer', 'localdbShimmer', 'apq3Shimmer', 'apq5Shimmer', 
                                        'apq11Shimmer', 'ddaShimmer'])  #add these lists to pandas in the right orde


In [56]:
pred

meanF0Hz   stdevF0Hz      HNR  localJitter  localabsoluteJitter  \
0  201.760556  162.401134  7.89608     0.031441             0.000164   

   rapJitter  ppq5Jitter  ddpJitter  localShimmer  localdbShimmer  \
0   0.015739    0.016306   0.047218      0.149788        1.300907   

   apq3Shimmer  apq5Shimmer  apq11Shimmer  ddaShimmer  
0     0.055637     0.077863      0.102166     0.16691

In [57]:
model.predict(pred)

array([1.])

In [58]:
# create lists to put the results
file_list = []
mean_F0_list = []
sd_F0_list = []
hnr_list = []
localJitter_list = []
localabsoluteJitter_list = []
rapJitter_list = []
ppq5Jitter_list = []
ddpJitter_list = []
localShimmer_list = []
localdbShimmer_list = []
apq3Shimmer_list = []
aqpq5Shimmer_list = []
apq11Shimmer_list = []
ddaShimmer_list = []
parkinson_list = []



# Go through all the wave files in the folder and measure pitch
for wave_file in glob.glob("C:/Users/srees/OneDrive/Desktop/major_proj/ParkinsonIA-master/audio/SpontaneousDialogue/HC/ID00_hc_0_0_0.wav"):
    sound = parselmouth.Sound(wave_file)
    (meanF0, stdevF0, hnr, localJitter, localabsoluteJitter, rapJitter, ppq5Jitter, ddpJitter, localShimmer, localdbShimmer, apq3Shimmer, aqpq5Shimmer, apq11Shimmer, ddaShimmer) = measurePitch(sound, 75, 1000, "Hertz")
    file_list.append(wave_file) # make an ID list
    mean_F0_list.append(meanF0) # make a mean F0 list
    sd_F0_list.append(stdevF0) # make a sd F0 list
    hnr_list.append(hnr)
    localJitter_list.append(localJitter)
    localabsoluteJitter_list.append(localabsoluteJitter)
    rapJitter_list.append(rapJitter)
    ppq5Jitter_list.append(ppq5Jitter)
    ddpJitter_list.append(ddpJitter)
    localShimmer_list.append(localShimmer)
    localdbShimmer_list.append(localdbShimmer)
    apq3Shimmer_list.append(apq3Shimmer)
    aqpq5Shimmer_list.append(aqpq5Shimmer)
    apq11Shimmer_list.append(apq11Shimmer)
    ddaShimmer_list.append(ddaShimmer)


pred = pd.DataFrame(np.column_stack([mean_F0_list, sd_F0_list, hnr_list, localJitter_list, localabsoluteJitter_list, rapJitter_list, ppq5Jitter_list, ddpJitter_list, localShimmer_list, localdbShimmer_list, apq3Shimmer_list, aqpq5Shimmer_list, apq11Shimmer_list, ddaShimmer_list]),
                               columns=['meanF0Hz', 'stdevF0Hz', 'HNR', 'localJitter', 'localabsoluteJitter', 'rapJitter', 
                                        'ppq5Jitter', 'ddpJitter', 'localShimmer', 'localdbShimmer', 'apq3Shimmer', 'apq5Shimmer', 
                                        'apq11Shimmer', 'ddaShimmer'])  #add these lists to pandas in the right orde


In [59]:
pred

meanF0Hz  stdevF0Hz        HNR  localJitter  localabsoluteJitter  \
0  191.272884  78.724991  14.258303      0.02514             0.000133   

   rapJitter  ppq5Jitter  ddpJitter  localShimmer  localdbShimmer  \
0   0.011398    0.013116   0.034195      0.112764        1.085513   

   apq3Shimmer  apq5Shimmer  apq11Shimmer  ddaShimmer  
0     0.045074     0.065806      0.112174    0.135223

In [60]:
model.predict(pred)

array([0.])

In [62]:
import joblib
joblib.dump(model, "model123.sav")

['model123.sav']